grpc:
  server:
    port: 59091
  client:
    echo:
      address: 'static://localhost:59091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: collector

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8081